/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem.employeepkg;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import static java.time.Clock.system;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import managementsystem.DB;
import managementsystem.employee;
import managementsystem.validation;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BBR
 */
public class Emp_Info extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    private String gender = "";
    private ImageIcon format = null;
    String filename = null;
    String aa = null;
    int w = 0;
    int q = 0;

    byte[] person_image = null;
    String i = null;
    String dd = null;
    int v = 0;

    /**
     * Creates new form Emp_Info
     */
    public Emp_Info() {
        initComponents();
        try {
            conn = DB.mycon();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Emp_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Emp_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Converted String: " + date1());
        jLabel15.setText(date1());
    }

    //date
    public String date1() {
        Date date = Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String Date = dateFormat.format(date);
        return Date;
    }

    //age validation 
    public Boolean age(String a) {
        String[] units = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().split("-");
        int year = Integer.parseInt(units[0]);
        System.out.println("BY :" + year);

        //now Year
        String NowDate = jLabel15.getText();
        String[] Nunits = NowDate.split("-");
        int Nyear = Integer.parseInt(Nunits[0]);
        System.out.println("NY :" + Nyear);

        //Age Balance
        v = Nyear - year;
        System.out.println("Age :" + v);
        if (v > 18) {
            return true;
        }
        JOptionPane.showMessageDialog(null, "Age must be above 18");
        return false;
    }

    public Boolean ageempty(String a) {

        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Select the Gender ");
            return false;

        }
        return true;

    }
    //

    //
    public void clear() {
        id_box.setText("");
        firstname_box.setText("");
        surname_box.setText("");
//        Tdob_box.setText("");
        email_box.setText("");
        contact_box.setText("");
        address_box.setText("");
        postcode_box.setText("");
        c_dep.setSelectedIndex(0);
        r_male.setSelected(false);
        r_female.setSelected(false);
        desig_box.setText("");
        datehired_box.setText("");
//        sallary_box.setText("");
        job_box.setText("");
        c_status.setSelectedIndex(0);
//        date_hire_box.setText("");
        id_box.setText("");
        pass.setText("");
        search_box.setText("");
        img.setIcon(null);
        jDateChooser1.setCalendar(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        surname_box = new javax.swing.JTextField();
        firstname_box = new javax.swing.JTextField();
        email_box = new javax.swing.JTextField();
        contact_box = new javax.swing.JTextField();
        address_box = new javax.swing.JTextField();
        postcode_box = new javax.swing.JTextField();
        desig_box = new javax.swing.JTextField();
        job_box = new javax.swing.JTextField();
        r_female = new javax.swing.JRadioButton();
        r_male = new javax.swing.JRadioButton();
        search_box = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        c_dep = new javax.swing.JComboBox<>();
        c_status = new javax.swing.JComboBox<>();
        id_box = new javax.swing.JLabel();
        datehired_box = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(943, 587));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Registration");

        jButton7.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton7.setText("Main Menu");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 727, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 130));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel3.setText("Employee ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel4.setText("First Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel5.setText("Surname");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel7.setText("Date of birth : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel8.setText("Email :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel9.setText("Contact :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 690, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel10.setText("Address :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 740, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel11.setText("Postcode :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 800, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel12.setText("Department :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel13.setText("Designation :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel14.setText("Date Hired :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel16.setText("Job Title :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel17.setText("Status :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        surname_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(surname_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 210, -1));

        firstname_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(firstname_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 210, -1));

        email_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(email_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 210, -1));

        contact_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(contact_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 680, 210, -1));

        address_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(address_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 210, -1));

        postcode_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(postcode_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 790, 210, -1));

        desig_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(desig_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 260, -1));

        job_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(job_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 260, -1));

        r_female.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        r_male.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel1.add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, -1));

        search_box.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        search_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_boxKeyReleased(evt);
            }
        });
        jPanel1.add(search_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 470, -1));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel2.setText("Search Employee :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 872, 170, 50));

        jButton2.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton2.setText("Add Record");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 870, 180, 50));

        jButton3.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton3.setText("Update Record");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 872, -1, 50));

        jButton4.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton4.setText("Attach");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 680, 400, 50));

        jButton5.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 872, 160, 50));

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 350, 400, 300));

        c_dep.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        c_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Department", "Finance", "HR", "Products" }));
        jPanel1.add(c_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 260, -1));

        c_status.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        c_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jPanel1.add(c_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 260, -1));

        id_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(id_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 210, 40));

        datehired_box.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(datehired_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 260, 30));

        jLabel18.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel18.setText("Password :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        pass.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 210, -1));

        jButton6.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jButton6.setText("View All Employees");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 872, -1, 50));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 210, 30));

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(1550, 995));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String bsal = "25000";
        String otrate = "500";
        String date = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        System.out.println("date :" + date);

        try {
            String sql = "SELECT `id` FROM `staff_information` WHERE `id`=('" + id_box.getText() + "')";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));;
            i = jTable1.getValueAt(0, 0).toString();

        } catch (Exception e) {
            System.out.println(e);
        }
        // FInd max id

        try {
            String sq2 = "SELECT MAX(id) FROM `staff_information`";
            pst = conn.prepareStatement(sq2);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));;
            aa = jTable2.getValueAt(0, 0).toString();
            q = Integer.parseInt(aa);
            w = q++;
            System.out.println(q);
        } catch (Exception e) {
            System.out.println(e);
        }
//        if (id_box.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No Data to Add");
//        }

        try {

            validation d = new validation();

            if (validation.isValidName(firstname_box.getText())
                    && validation.isValidSurName(surname_box.getText())
                    && validation.isValidGender(gender)
                    && ageempty(date)
                    //                    && validation.isValidBdate(Tdob_box.getText())
                    && validation.isValidEmail(email_box.getText())
                    && validation.isValidPhoneNumber(contact_box.getText())
                    && validation.isValidPcode(postcode_box.getText())
                    && validation.isValidDesig(desig_box.getText())
                    && validation.isValidDept(c_dep.getSelectedItem().toString())
                    && age(date)) {
                int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save?");
                if (x == 0) {
                    String sql = "INSERT INTO staff_information (gender,first_name,surname,Dob,Email,Telephone,Address,Department,Salary,Post_code,Designation,Status,job_title,image,pwd,ot_rate)"
                            + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, gender);
                    pst.setString(2, firstname_box.getText());
                    pst.setString(3, surname_box.getText());
                    //date
                    pst.setString(4, date);
                    pst.setString(5, email_box.getText());
                    pst.setString(6, contact_box.getText());
                    pst.setString(7, address_box.getText());
                    pst.setString(8, c_dep.getSelectedItem().toString());
                    pst.setString(9, bsal);
                    pst.setString(10, postcode_box.getText());
                    pst.setString(11, desig_box.getText());
                    pst.setString(12, c_status.getSelectedItem().toString());
                    pst.setString(13, job_box.getText());
                    pst.setBytes(14, person_image);
                    pst.setString(15, pass.getText());
                    pst.setString(16, otrate);

                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Added");
                    clear();

                    // create attendence table
                    try {
                        String sq = "CREATE TABLE eat" + q + " (`id` int(255) PRIMARY KEY AUTO_INCREMENT, `count` int(255) NOT NULL,"
                                + " `date` varchar(20) NULL, `in` varchar(20) NULL, `out` varchar(20) NULL, `month` int(20) NOT NULL,"
                                + " `OThours` INT(5) NULL, `status` varchar(20) NULL ,`Reason` varchar(50) )";
                        System.out.println(sq);

                        pst = conn.prepareStatement(sq);
                        pst.execute();

                    } catch (Exception e) {
                        System.out.println(e + "Attendence Record Table is not Created ");
                    }
                }
            } else {

            }

        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = id_box.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Select an Id to Delete !");
        } else {
            try {
                int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Delete?");
                if (x == 0) {
                    String sql = "DELETE FROM `staff_information` WHERE `id`=('" + id + "')";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Deleted !");
                    clear();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            //drop table in attendence
            try {

                String sql = "DROP TABLE `eat" + id + "`";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Attencdece also Deleted !");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);


    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here: 
        gender = "Female";
        r_male.setSelected(false);
        r_female.setSelected(true);

    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);

        try {
            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];

            for (int number; (number = fix.read(buff)) != -1;) {
                bos.write(buff, 0, number);
            }
            person_image = bos.toByteArray();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void search_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyReleased
        // TODO add your handling code here:
        String a = search_box.getText();
        if (!a.equals("")) {
            try {

                String sql = "SELECT * FROM `staff_information` WHERE id='" + a + "'";

                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                String id = jTable1.getValueAt(0, 0).toString();
                id_box.setText(id);

                String add2 = jTable1.getValueAt(0, 1).toString();
                firstname_box.setText(add2);

                String add3 = jTable1.getValueAt(0, 2).toString();
                surname_box.setText(add3);

                String add4 = jTable1.getValueAt(0, 3).toString();
                ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText(add4);

                String add5 = jTable1.getValueAt(0, 4).toString();
                email_box.setText(add5);

                String add15 = jTable1.getValueAt(0, 14).toString();
                if (add15.equals("Male")) {
                    r_male.setSelected(true);
                    r_female.setSelected(false);
                } else {
                    r_female.setSelected(true);
                    r_male.setSelected(false);

                }

                String add17 = jTable1.getValueAt(0, 16).toString();
                pass.setText(add17);

                String add6 = jTable1.getValueAt(0, 5).toString();
                contact_box.setText(add6);

                String add7 = jTable1.getValueAt(0, 6).toString();
                address_box.setText(add7);

                String add10 = jTable1.getValueAt(0, 9).toString();
                postcode_box.setText(add10);

                String add8 = jTable1.getValueAt(0, 7).toString();
                switch (add8) {
                    case "Products":
                        c_dep.setSelectedIndex(3);
                        break;
                    case "Finance":
                        c_dep.setSelectedIndex(1);
                        break;
                    case "HR":
                        c_dep.setSelectedIndex(2);
                        break;
                    default:
                        c_dep.setSelectedIndex(0);
                        break;
                }

                String add11 = jTable1.getValueAt(0, 10).toString();
                desig_box.setText(add11);

                String add13 = jTable1.getValueAt(0, 12).toString();
                datehired_box.setText(add13);

                String add14 = jTable1.getValueAt(0, 13).toString();
                job_box.setText(add14);

                String add12 = jTable1.getValueAt(0, 11).toString();
                if (add12.equals("Active")) {
                    c_status.setSelectedIndex(0);
                } else {
                    c_status.setSelectedIndex(1);
                }

                try {
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery("SELECT * FROM `staff_information` WHERE id='" + a + "'");
                    System.out.println("SELECT `image` FROM `staff_information` WHERE id='" + a + "'");

                    if (rs.next()) {
                        byte[] iimg = rs.getBytes("image");
                        ImageIcon image = new ImageIcon(iimg);
                        Image im = image.getImage();
                        Image myimage = im.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT);
                        ImageIcon newImage = new ImageIcon(myimage);
                        img.setIcon(newImage);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }

        } else {
            clear();
        }

        if (!id_box.getText().equals("")) {
            jButton2.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_search_boxKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = id_box.getText();
        String date1 = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();

        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Select an Id to Delete !");
        } else {
            try {
                if (validation.isValidName(firstname_box.getText())
                        && validation.isValidSurName(surname_box.getText())
                        && validation.isValidGender(gender)
                        && ageempty(date1)
                        && validation.isValidEmail(email_box.getText())
                        && validation.isValidPhoneNumber(contact_box.getText())
                        && validation.isValidPcode(postcode_box.getText())
                        && validation.isValidDesig(desig_box.getText())
                        && validation.isValidDept(c_dep.getSelectedItem().toString())
                        && age(date1)) {
                    String val0 = id_box.getText();
                    String add1 = firstname_box.getText();
                    String add2 = surname_box.getText();
                    String date = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
                    String add4 = email_box.getText();
                    String add5 = contact_box.getText();
                    String add6 = address_box.getText();
                    String add7 = c_dep.getSelectedItem().toString();
                    String add9 = postcode_box.getText();
                    String add10 = desig_box.getText();
                    String add11 = c_status.getSelectedItem().toString();
                    String add12 = job_box.getText();
                    String add14 = pass.getText();

                    int x = JOptionPane.showConfirmDialog(null, "Do you really want to Update ?");
                    if (x == 0) {

                        String sql = "UPDATE `staff_information` SET `first_name`=('" + add1 + "'),`surname`=('" + add2 + "')"
                                + ",`Dob`=('" + date + "'),`Email`=('" + add4 + "'),`Telephone`=('" + add5 + "'),`Address`=('" + add6 + "'),"
                                + "`Department`=('" + add7 + "'),`Post_code`=('" + add9 + "')"
                                + ",`Designation`=('" + add10 + "'),`Status`=('" + add11 + "'),"
                                + "`job_title`=('" + add12 + "'),`gender`=('" + gender + "'),`pwd`=('" + add14 + "')"
                                + "WHERE `id`=('" + val0 + "')";
                        pst = conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Updated !");
                    }
                } else {

                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void search_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyPressed

    }//GEN-LAST:event_search_boxKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clear();
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        All_Emp a1 = new All_Emp();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new employee().setVisible(true);
        this.dispose();
        //system s = new system();
       // s.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        // TODO add your handling code here:
        String id = id_box.getText();
        String p = pass.getText();
        String z = "";

        try {
            String sql = "SELECT pwd FROM `eat" + id + "`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            z = jTable1.getValueAt(0, 0).toString();
        } catch (Exception e) {
            System.out.println(e);
        }

        if (z.equals(p)) {
            jButton1.setEnabled(true);

        } else {
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_passKeyReleased

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));

    }//GEN-LAST:event_jButton3MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));

    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));

    }//GEN-LAST:event_jButton6MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButton7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField address_box;
    public static javax.swing.JComboBox<String> c_dep;
    public static javax.swing.JComboBox<String> c_status;
    public static javax.swing.JTextField contact_box;
    public static javax.swing.JLabel datehired_box;
    public static javax.swing.JTextField desig_box;
    public static javax.swing.JTextField email_box;
    public static javax.swing.JTextField firstname_box;
    public static javax.swing.JLabel id_box;
    public static javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JTextField job_box;
    public static javax.swing.JTextField pass;
    public static javax.swing.JTextField postcode_box;
    public static javax.swing.JRadioButton r_female;
    public static javax.swing.JRadioButton r_male;
    private javax.swing.JTextField search_box;
    public static javax.swing.JTextField surname_box;
    // End of variables declaration//GEN-END:variables
}
