/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem.inventorypkg;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import static com.itextpdf.text.pdf.PdfName.F;
import com.itextpdf.text.pdf.PdfPCell;

import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import managementsystem.ButtonConfig;
import managementsystem.DB;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report_main
     */
    public report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 70)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("reports");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 101, 385, 10));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("<");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 30, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(210, 210, 210));
        jPanel6.setPreferredSize(new java.awt.Dimension(209, 192));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managementsystem/Images/inventory/thin-096_clipboard_inventory_box_import_download-512.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("stock request report");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, -1));

        jPanel8.setBackground(new java.awt.Color(210, 210, 210));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managementsystem/Images/inventory/thin-097_clipboard_inventory_box_archive-512.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("inventory report");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(29, 29, 29))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        new loginoptions().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream("StockRequestReport.pdf"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.open();
        try {
            
           
            String date = new Date().toString();
            document.add(new Paragraph("Stock Request Report", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Font.BOLD, BaseColor.BLACK)));
            document.add(new Paragraph("   "));
            document.add(new Paragraph("Report issued on '"+date+"'"));
            document.add(new Paragraph("   "));
            document.add(new Paragraph("The following report shows the stock that has been requested from Rajapura Wedhamadura"));
            //document.add(new Paragraph("Note: The following requests have also been confirmed by the admin of Rajapura Wedhamadura", FontFactory.getFont(FontFactory.HELVETICA, Font.ITALIC)));
            document.add(new Paragraph("   "));
            document.add(new Paragraph("   "));
            document.add(new Paragraph("   "));
            PdfPTable table = new PdfPTable(8);
            table.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell(new Paragraph("Table Name"));
            cell.setColspan(8);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            table.addCell(cell);
            
            table.addCell("Product ID");
            table.addCell("Product Name");
            table.addCell("Quantity");
            table.addCell("Special Requirements");
            table.addCell("Supplier ID");
            table.addCell("Supplier Name");
            table.addCell("Suplier Email");
            table.addCell("Date Added");
            
            
            try{
        Connection c = DB.mycon();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT product_id, product_name, quantity, special_requirements, supplier_id, supplier_name, supplier_email, Date  FROM stock_requests where status = 1";
        pst = c.prepareStatement(sql);
        pst.executeQuery();
        rs = pst.getResultSet();
        while (rs.next()){
            table.addCell(rs.getString("product_id"));
            table.addCell(rs.getString("product_name"));
            table.addCell(rs.getString("quantity"));
            table.addCell(rs.getString("special_requirements"));
            table.addCell(rs.getString("supplier_id"));
            table.addCell(rs.getString("supplier_name"));
            table.addCell(rs.getString("supplier_email"));
            table.addCell(rs.getString("Date"));
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
            document.add(table);
            //com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("raja_1.png");
            //Image img = Image.getInstance("raja_1.png");
            //document.add(logo);
            
        } catch (DocumentException ex) {
            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
                    com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("raja_1.png");
//                com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("logo.png");
//                logo.setAlignment(Image.ALIGN_TOP);
//                logo.setAlignment(Image.ALIGN_RIGHT);
//                logo.scaleAbsolute(180,79);
                document.add(logo);
//                document.add(new Paragraph("   "));
//
            } catch (BadElementException ex) {
                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        document.close();
        
       int x= JOptionPane.showConfirmDialog(null, "Report Saved! Do you want to open?");
        if(x==0){
            try{
                Desktop.getDesktop().open(new File("‪‪F://ManagementSystem//StockRequestReport.pdf"));
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        else if (x==1){
            JOptionPane.showMessageDialog(null, "Report Saved");
        }
       
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        ButtonConfig.resetColor(jPanel6);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        ButtonConfig.resetColor2(jPanel6);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        
        
        
//        Document document = new Document();
//        try {
//            PdfWriter.getInstance(document, new FileOutputStream("InventoryReport.pdf"));
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (DocumentException ex) {
//            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        document.open();
//        try {
////            try {
////                com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("logo.png");
////                logo.setAlignment(Image.ALIGN_TOP);
////                logo.setAlignment(Image.ALIGN_RIGHT);
////                logo.scaleAbsolute(180,79);
////                document.add(logo);
////                document.add(new Paragraph("   "));
////
////            } catch (BadElementException ex) {
////                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
////            } catch (IOException ex) {
////                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
////            }
//            String date = new Date().toString();
//            document.add(new Paragraph("Inventory Report", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Font.BOLD, BaseColor.BLACK)));
//            document.add(new Paragraph("   "));
//            document.add(new Paragraph("Report issued on '"+date+"'"));
//            document.add(new Paragraph("   "));
//            document.add(new Paragraph("The following report shows the stock available in Rajapura Wedhamadura's Inventory"));
//            document.add(new Paragraph("   "));
//            document.add(new Paragraph("   "));
//            document.add(new Paragraph("   "));
//            PdfPTable table = new PdfPTable(7);
//            table.setWidthPercentage(100);
//            PdfPCell cell = new PdfPCell(new Paragraph("Table Name"));
//            cell.setColspan(7);
//            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
//            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
//            table.addCell(cell);
//            
//            table.addCell("Product ID");
//            table.addCell("Product Name");
//            table.addCell("Product Description");
//            table.addCell("Unit Price");
//            table.addCell("Quantity");
//            table.addCell("Total Amount");
//            table.addCell("Date Added");
//            
//            
//            try{
//        Connection c = DB.mycon();
//        PreparedStatement pst = null;
//        ResultSet rs = null;
//        String sql = "SELECT product_id, product_name, product_description, unit_price, quantity, total_amount, Date  FROM inventory_add";
//        pst = c.prepareStatement(sql);
//        pst.executeQuery();
//        rs = pst.getResultSet();
//        while (rs.next()){
//            table.addCell(rs.getString("product_id"));
//            table.addCell(rs.getString("product_name"));
//            table.addCell(rs.getString("product_description"));
//            table.addCell(rs.getString("unit_price"));
//            table.addCell(rs.getString("quantity"));
//            table.addCell(rs.getString("total_amount"));
//            table.addCell(rs.getString("Date"));
//        }
//        }
//        catch(Exception e){
//            e.printStackTrace();
//        }
//            
//            document.add(table);
//            
//        } catch (DocumentException ex) {
//            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
//        }
////        try {
////                    com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("raja_1.png");
//////                com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("logo.png");
//////                logo.setAlignment(Image.ALIGN_TOP);
//////                logo.setAlignment(Image.ALIGN_RIGHT);
//////                logo.scaleAbsolute(180,79);
////                document.add(logo);
//////                document.add(new Paragraph("   "));
//////
////            } catch (BadElementException ex) {
////                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
////            } catch (IOException ex) {
////                Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
////            } catch (DocumentException ex) {
////            Logger.getLogger(report.class.getName()).log(Level.SEVERE, null, ex);
////        }
//        document.close();
//        //Desktop.getDesktop().open(new File("F:\ManagementSystem"));
//        //JOptionPane.showMessageDialog(null, "Report Saved");
//        int x= JOptionPane.showConfirmDialog(null, "Report Saved! Do you want to open?");
//        if(x==0){
//            try{
//                Desktop.getDesktop().open(new File("‪‪C:/Users/KALINDU/Documents/NetBeansProjects/ManagementSystem/InventoryReport.pdf"));
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//        }
//        else if (x==1){
//            JOptionPane.showMessageDialog(null, "Report Saved");
//        }

        String product_id = null;
        String product_name = null;   
        String product_description = null;
        String unit_price = null;
        String quantity = null;
        String total_amount = null;
        String date = null;
        try {
        Connection c = DB.mycon();
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("SELECT *  FROM inventory_add");
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream("InventoryReport.pdf"));
        document.open();          
        document.add(new Paragraph("Inventory Report",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
        document.add(new Paragraph("  "));
        document.add(new Paragraph(new Date().toString()));
        document.add(new Paragraph("The following report shows the stock available in Rajapura Wedhamadura's Inventory"));
        document.add(new Paragraph("____________________________________________________________________________"));
        document.add(new Paragraph("   "));
        PdfPTable table = new PdfPTable(7);
        table.setWidthPercentage(110);
        PdfPCell cell=new PdfPCell(new Paragraph("Inventory Details"));
        cell.setColspan(7);
        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        cell.setBackgroundColor(BaseColor.GRAY);
        table.addCell(cell);
        PdfPCell cell1=new PdfPCell(new Paragraph("product id"));
        cell1.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell1);
        PdfPCell cell2=new PdfPCell(new Paragraph("product name"));
        cell2.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell2);
        PdfPCell cell3=new PdfPCell(new Paragraph("product description"));
        cell3.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell3);
        PdfPCell cell4=new PdfPCell(new Paragraph("unit price"));
        cell4.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell4);
        PdfPCell cell5=new PdfPCell(new Paragraph("quantity"));
        cell5.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell5);
        PdfPCell cell6=new PdfPCell(new Paragraph("total amount"));
        cell6.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell6);
        PdfPCell cell7=new PdfPCell(new Paragraph("Date"));
        cell7.setBackgroundColor(BaseColor.LIGHT_GRAY);
        table.addCell(cell7);
           
        while (rs.next()) {
            
            product_id = (rs.getString("product_id"));
            product_name = (rs.getString("product_name"));
            product_description = (rs.getString("product_description"));
            unit_price = (rs.getString("unit_price"));
            quantity = (rs.getString("quantity"));
            total_amount=(rs.getString("total_amount"));
            date=(rs.getString(("Date")));

            table.addCell(product_id);
            table.addCell(product_name);
            table.addCell(product_description);
            table.addCell(unit_price);
            table.addCell(quantity);
            table.addCell(total_amount);
            table.addCell(date);
           

        }
        document.add(table);
        Image image = Image.getInstance("raja_1.png");
        document.add(image);
        document.close();
        int x = JOptionPane.showConfirmDialog(rootPane, "Report Saved. Do you want to open?");
        if (x==0){
            try{
             
               Desktop.getDesktop().open(new File("C:/Users/KALINDU/Documents/NetBeansProjects/ManagementSystem/InventoryReport.pdf"));

            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error!");
            }
        
        
        }else if(x==1) {
            JOptionPane.showMessageDialog(null, "Report Saved to HDD!");  
        } 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error!");
        e.printStackTrace();
    }





    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        ButtonConfig.resetColor(jPanel8);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        ButtonConfig.resetColor2(jPanel8);
    }//GEN-LAST:event_jPanel8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
